### ISSUE TITLE
Sort resolved tags as versions and not as strings

### ISSUE THREAD

**Issue by gtsopour** [rollwagen/tf-module-versions#14]
@rollwagen At the moment, the latest tag is not always resolved properly. The main reason is that the code sorts the resolved tags as strings instead of versions. Please find a suggestion below.

# validater/main.go
`sort.Sort(sortedVersions(availableVersions))` instead of `sort.Strings(availableVersions)`

# validater/sorted_versions.go (new)
```
package validater

import (
	"github.com/hashicorp/go-version"
)

type sortedVersions []string

func (s sortedVersions) Len() int {
	return len(s)
}

func (s sortedVersions) Swap(i, j int) {
	s[i], s[j] = s[j], s[i]
}

func (s sortedVersions) Less(i, j int) bool {
	v1, err := version.NewVersion(s[i])
	if err != nil {
			panic(err)
	}
	v2, err := version.NewVersion(s[j])
	if err != nil {
			panic(err)
	}
	return v1.LessThan(v2)
}
```

**Comment by rollwagen** [comment]
Closed by #15
